CREATE DATABASE ChurnAnalysis

USE ChurnAnalysis


Select TOP 5 * From churn_Cleaned


SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'churn_Cleaned'
ORDER BY ORDINAL_POSITION